// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bot.proto

package bot

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MessageType_Private MessageType = 0
	MessageType_Group   MessageType = 1
	MessageType_Discuss MessageType = 2
)

var MessageType_name = map[int32]string{
	0: "Private",
	1: "Group",
	2: "Discuss",
}

var MessageType_value = map[string]int32{
	"Private": 0,
	"Group":   1,
	"Discuss": 2,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{0}
}

type GroupApplicationType int32

const (
	GroupApplicationType_Add    GroupApplicationType = 0
	GroupApplicationType_Invite GroupApplicationType = 1
)

var GroupApplicationType_name = map[int32]string{
	0: "Add",
	1: "Invite",
}

var GroupApplicationType_value = map[string]int32{
	"Add":    0,
	"Invite": 1,
}

func (x GroupApplicationType) String() string {
	return proto.EnumName(GroupApplicationType_name, int32(x))
}

func (GroupApplicationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{1}
}

type DeleteMessageRequest struct {
	MessageId            int64    `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMessageRequest) Reset()         { *m = DeleteMessageRequest{} }
func (m *DeleteMessageRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMessageRequest) ProtoMessage()    {}
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{0}
}

func (m *DeleteMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMessageRequest.Unmarshal(m, b)
}
func (m *DeleteMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMessageRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMessageRequest.Merge(m, src)
}
func (m *DeleteMessageRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMessageRequest.Size(m)
}
func (m *DeleteMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMessageRequest proto.InternalMessageInfo

func (m *DeleteMessageRequest) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

type DeleteMessageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMessageResponse) Reset()         { *m = DeleteMessageResponse{} }
func (m *DeleteMessageResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMessageResponse) ProtoMessage()    {}
func (*DeleteMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{1}
}

func (m *DeleteMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMessageResponse.Unmarshal(m, b)
}
func (m *DeleteMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMessageResponse.Marshal(b, m, deterministic)
}
func (m *DeleteMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMessageResponse.Merge(m, src)
}
func (m *DeleteMessageResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMessageResponse.Size(m)
}
func (m *DeleteMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMessageResponse proto.InternalMessageInfo

type LikeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikeRequest) Reset()         { *m = LikeRequest{} }
func (m *LikeRequest) String() string { return proto.CompactTextString(m) }
func (*LikeRequest) ProtoMessage()    {}
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{2}
}

func (m *LikeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikeRequest.Unmarshal(m, b)
}
func (m *LikeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikeRequest.Marshal(b, m, deterministic)
}
func (m *LikeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikeRequest.Merge(m, src)
}
func (m *LikeRequest) XXX_Size() int {
	return xxx_messageInfo_LikeRequest.Size(m)
}
func (m *LikeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LikeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LikeRequest proto.InternalMessageInfo

type LikeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikeResponse) Reset()         { *m = LikeResponse{} }
func (m *LikeResponse) String() string { return proto.CompactTextString(m) }
func (*LikeResponse) ProtoMessage()    {}
func (*LikeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{3}
}

func (m *LikeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikeResponse.Unmarshal(m, b)
}
func (m *LikeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikeResponse.Marshal(b, m, deterministic)
}
func (m *LikeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikeResponse.Merge(m, src)
}
func (m *LikeResponse) XXX_Size() int {
	return xxx_messageInfo_LikeResponse.Size(m)
}
func (m *LikeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LikeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LikeResponse proto.InternalMessageInfo

type KickChatMemberRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickChatMemberRequest) Reset()         { *m = KickChatMemberRequest{} }
func (m *KickChatMemberRequest) String() string { return proto.CompactTextString(m) }
func (*KickChatMemberRequest) ProtoMessage()    {}
func (*KickChatMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{4}
}

func (m *KickChatMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickChatMemberRequest.Unmarshal(m, b)
}
func (m *KickChatMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickChatMemberRequest.Marshal(b, m, deterministic)
}
func (m *KickChatMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickChatMemberRequest.Merge(m, src)
}
func (m *KickChatMemberRequest) XXX_Size() int {
	return xxx_messageInfo_KickChatMemberRequest.Size(m)
}
func (m *KickChatMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KickChatMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KickChatMemberRequest proto.InternalMessageInfo

type KickChatMemberResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickChatMemberResponse) Reset()         { *m = KickChatMemberResponse{} }
func (m *KickChatMemberResponse) String() string { return proto.CompactTextString(m) }
func (*KickChatMemberResponse) ProtoMessage()    {}
func (*KickChatMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{5}
}

func (m *KickChatMemberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickChatMemberResponse.Unmarshal(m, b)
}
func (m *KickChatMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickChatMemberResponse.Marshal(b, m, deterministic)
}
func (m *KickChatMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickChatMemberResponse.Merge(m, src)
}
func (m *KickChatMemberResponse) XXX_Size() int {
	return xxx_messageInfo_KickChatMemberResponse.Size(m)
}
func (m *KickChatMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KickChatMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KickChatMemberResponse proto.InternalMessageInfo

type RestrictChatMemberRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestrictChatMemberRequest) Reset()         { *m = RestrictChatMemberRequest{} }
func (m *RestrictChatMemberRequest) String() string { return proto.CompactTextString(m) }
func (*RestrictChatMemberRequest) ProtoMessage()    {}
func (*RestrictChatMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{6}
}

func (m *RestrictChatMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestrictChatMemberRequest.Unmarshal(m, b)
}
func (m *RestrictChatMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestrictChatMemberRequest.Marshal(b, m, deterministic)
}
func (m *RestrictChatMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestrictChatMemberRequest.Merge(m, src)
}
func (m *RestrictChatMemberRequest) XXX_Size() int {
	return xxx_messageInfo_RestrictChatMemberRequest.Size(m)
}
func (m *RestrictChatMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestrictChatMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestrictChatMemberRequest proto.InternalMessageInfo

type RestrictChatMemberResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestrictChatMemberResponse) Reset()         { *m = RestrictChatMemberResponse{} }
func (m *RestrictChatMemberResponse) String() string { return proto.CompactTextString(m) }
func (*RestrictChatMemberResponse) ProtoMessage()    {}
func (*RestrictChatMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{7}
}

func (m *RestrictChatMemberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestrictChatMemberResponse.Unmarshal(m, b)
}
func (m *RestrictChatMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestrictChatMemberResponse.Marshal(b, m, deterministic)
}
func (m *RestrictChatMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestrictChatMemberResponse.Merge(m, src)
}
func (m *RestrictChatMemberResponse) XXX_Size() int {
	return xxx_messageInfo_RestrictChatMemberResponse.Size(m)
}
func (m *RestrictChatMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestrictChatMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestrictChatMemberResponse proto.InternalMessageInfo

type RestrictAnonymousChatMemberRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestrictAnonymousChatMemberRequest) Reset()         { *m = RestrictAnonymousChatMemberRequest{} }
func (m *RestrictAnonymousChatMemberRequest) String() string { return proto.CompactTextString(m) }
func (*RestrictAnonymousChatMemberRequest) ProtoMessage()    {}
func (*RestrictAnonymousChatMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{8}
}

func (m *RestrictAnonymousChatMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestrictAnonymousChatMemberRequest.Unmarshal(m, b)
}
func (m *RestrictAnonymousChatMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestrictAnonymousChatMemberRequest.Marshal(b, m, deterministic)
}
func (m *RestrictAnonymousChatMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestrictAnonymousChatMemberRequest.Merge(m, src)
}
func (m *RestrictAnonymousChatMemberRequest) XXX_Size() int {
	return xxx_messageInfo_RestrictAnonymousChatMemberRequest.Size(m)
}
func (m *RestrictAnonymousChatMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestrictAnonymousChatMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestrictAnonymousChatMemberRequest proto.InternalMessageInfo

type RestrictAnonymousChatMemberResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestrictAnonymousChatMemberResponse) Reset()         { *m = RestrictAnonymousChatMemberResponse{} }
func (m *RestrictAnonymousChatMemberResponse) String() string { return proto.CompactTextString(m) }
func (*RestrictAnonymousChatMemberResponse) ProtoMessage()    {}
func (*RestrictAnonymousChatMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{9}
}

func (m *RestrictAnonymousChatMemberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestrictAnonymousChatMemberResponse.Unmarshal(m, b)
}
func (m *RestrictAnonymousChatMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestrictAnonymousChatMemberResponse.Marshal(b, m, deterministic)
}
func (m *RestrictAnonymousChatMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestrictAnonymousChatMemberResponse.Merge(m, src)
}
func (m *RestrictAnonymousChatMemberResponse) XXX_Size() int {
	return xxx_messageInfo_RestrictAnonymousChatMemberResponse.Size(m)
}
func (m *RestrictAnonymousChatMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestrictAnonymousChatMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestrictAnonymousChatMemberResponse proto.InternalMessageInfo

type RestrictAllChatMembersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestrictAllChatMembersRequest) Reset()         { *m = RestrictAllChatMembersRequest{} }
func (m *RestrictAllChatMembersRequest) String() string { return proto.CompactTextString(m) }
func (*RestrictAllChatMembersRequest) ProtoMessage()    {}
func (*RestrictAllChatMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{10}
}

func (m *RestrictAllChatMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestrictAllChatMembersRequest.Unmarshal(m, b)
}
func (m *RestrictAllChatMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestrictAllChatMembersRequest.Marshal(b, m, deterministic)
}
func (m *RestrictAllChatMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestrictAllChatMembersRequest.Merge(m, src)
}
func (m *RestrictAllChatMembersRequest) XXX_Size() int {
	return xxx_messageInfo_RestrictAllChatMembersRequest.Size(m)
}
func (m *RestrictAllChatMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestrictAllChatMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestrictAllChatMembersRequest proto.InternalMessageInfo

type RestrictAllChatMembersResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestrictAllChatMembersResponse) Reset()         { *m = RestrictAllChatMembersResponse{} }
func (m *RestrictAllChatMembersResponse) String() string { return proto.CompactTextString(m) }
func (*RestrictAllChatMembersResponse) ProtoMessage()    {}
func (*RestrictAllChatMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{11}
}

func (m *RestrictAllChatMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestrictAllChatMembersResponse.Unmarshal(m, b)
}
func (m *RestrictAllChatMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestrictAllChatMembersResponse.Marshal(b, m, deterministic)
}
func (m *RestrictAllChatMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestrictAllChatMembersResponse.Merge(m, src)
}
func (m *RestrictAllChatMembersResponse) XXX_Size() int {
	return xxx_messageInfo_RestrictAllChatMembersResponse.Size(m)
}
func (m *RestrictAllChatMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestrictAllChatMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestrictAllChatMembersResponse proto.InternalMessageInfo

type PromoteChatMemberRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PromoteChatMemberRequest) Reset()         { *m = PromoteChatMemberRequest{} }
func (m *PromoteChatMemberRequest) String() string { return proto.CompactTextString(m) }
func (*PromoteChatMemberRequest) ProtoMessage()    {}
func (*PromoteChatMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{12}
}

func (m *PromoteChatMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromoteChatMemberRequest.Unmarshal(m, b)
}
func (m *PromoteChatMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromoteChatMemberRequest.Marshal(b, m, deterministic)
}
func (m *PromoteChatMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromoteChatMemberRequest.Merge(m, src)
}
func (m *PromoteChatMemberRequest) XXX_Size() int {
	return xxx_messageInfo_PromoteChatMemberRequest.Size(m)
}
func (m *PromoteChatMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PromoteChatMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PromoteChatMemberRequest proto.InternalMessageInfo

type PromoteChatMemberResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PromoteChatMemberResponse) Reset()         { *m = PromoteChatMemberResponse{} }
func (m *PromoteChatMemberResponse) String() string { return proto.CompactTextString(m) }
func (*PromoteChatMemberResponse) ProtoMessage()    {}
func (*PromoteChatMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{13}
}

func (m *PromoteChatMemberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromoteChatMemberResponse.Unmarshal(m, b)
}
func (m *PromoteChatMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromoteChatMemberResponse.Marshal(b, m, deterministic)
}
func (m *PromoteChatMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromoteChatMemberResponse.Merge(m, src)
}
func (m *PromoteChatMemberResponse) XXX_Size() int {
	return xxx_messageInfo_PromoteChatMemberResponse.Size(m)
}
func (m *PromoteChatMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PromoteChatMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PromoteChatMemberResponse proto.InternalMessageInfo

type EnableAnonymousChatRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableAnonymousChatRequest) Reset()         { *m = EnableAnonymousChatRequest{} }
func (m *EnableAnonymousChatRequest) String() string { return proto.CompactTextString(m) }
func (*EnableAnonymousChatRequest) ProtoMessage()    {}
func (*EnableAnonymousChatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{14}
}

func (m *EnableAnonymousChatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableAnonymousChatRequest.Unmarshal(m, b)
}
func (m *EnableAnonymousChatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableAnonymousChatRequest.Marshal(b, m, deterministic)
}
func (m *EnableAnonymousChatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableAnonymousChatRequest.Merge(m, src)
}
func (m *EnableAnonymousChatRequest) XXX_Size() int {
	return xxx_messageInfo_EnableAnonymousChatRequest.Size(m)
}
func (m *EnableAnonymousChatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableAnonymousChatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnableAnonymousChatRequest proto.InternalMessageInfo

type EnableAnonymousChatResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableAnonymousChatResponse) Reset()         { *m = EnableAnonymousChatResponse{} }
func (m *EnableAnonymousChatResponse) String() string { return proto.CompactTextString(m) }
func (*EnableAnonymousChatResponse) ProtoMessage()    {}
func (*EnableAnonymousChatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{15}
}

func (m *EnableAnonymousChatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableAnonymousChatResponse.Unmarshal(m, b)
}
func (m *EnableAnonymousChatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableAnonymousChatResponse.Marshal(b, m, deterministic)
}
func (m *EnableAnonymousChatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableAnonymousChatResponse.Merge(m, src)
}
func (m *EnableAnonymousChatResponse) XXX_Size() int {
	return xxx_messageInfo_EnableAnonymousChatResponse.Size(m)
}
func (m *EnableAnonymousChatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableAnonymousChatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnableAnonymousChatResponse proto.InternalMessageInfo

type SetChatMemberCardRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetChatMemberCardRequest) Reset()         { *m = SetChatMemberCardRequest{} }
func (m *SetChatMemberCardRequest) String() string { return proto.CompactTextString(m) }
func (*SetChatMemberCardRequest) ProtoMessage()    {}
func (*SetChatMemberCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{16}
}

func (m *SetChatMemberCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetChatMemberCardRequest.Unmarshal(m, b)
}
func (m *SetChatMemberCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetChatMemberCardRequest.Marshal(b, m, deterministic)
}
func (m *SetChatMemberCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetChatMemberCardRequest.Merge(m, src)
}
func (m *SetChatMemberCardRequest) XXX_Size() int {
	return xxx_messageInfo_SetChatMemberCardRequest.Size(m)
}
func (m *SetChatMemberCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetChatMemberCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetChatMemberCardRequest proto.InternalMessageInfo

type SetChatMemberCardResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetChatMemberCardResponse) Reset()         { *m = SetChatMemberCardResponse{} }
func (m *SetChatMemberCardResponse) String() string { return proto.CompactTextString(m) }
func (*SetChatMemberCardResponse) ProtoMessage()    {}
func (*SetChatMemberCardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{17}
}

func (m *SetChatMemberCardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetChatMemberCardResponse.Unmarshal(m, b)
}
func (m *SetChatMemberCardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetChatMemberCardResponse.Marshal(b, m, deterministic)
}
func (m *SetChatMemberCardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetChatMemberCardResponse.Merge(m, src)
}
func (m *SetChatMemberCardResponse) XXX_Size() int {
	return xxx_messageInfo_SetChatMemberCardResponse.Size(m)
}
func (m *SetChatMemberCardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetChatMemberCardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetChatMemberCardResponse proto.InternalMessageInfo

type SetChatMemberTitleRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetChatMemberTitleRequest) Reset()         { *m = SetChatMemberTitleRequest{} }
func (m *SetChatMemberTitleRequest) String() string { return proto.CompactTextString(m) }
func (*SetChatMemberTitleRequest) ProtoMessage()    {}
func (*SetChatMemberTitleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{18}
}

func (m *SetChatMemberTitleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetChatMemberTitleRequest.Unmarshal(m, b)
}
func (m *SetChatMemberTitleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetChatMemberTitleRequest.Marshal(b, m, deterministic)
}
func (m *SetChatMemberTitleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetChatMemberTitleRequest.Merge(m, src)
}
func (m *SetChatMemberTitleRequest) XXX_Size() int {
	return xxx_messageInfo_SetChatMemberTitleRequest.Size(m)
}
func (m *SetChatMemberTitleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetChatMemberTitleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetChatMemberTitleRequest proto.InternalMessageInfo

type SetChatMemberTitleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetChatMemberTitleResponse) Reset()         { *m = SetChatMemberTitleResponse{} }
func (m *SetChatMemberTitleResponse) String() string { return proto.CompactTextString(m) }
func (*SetChatMemberTitleResponse) ProtoMessage()    {}
func (*SetChatMemberTitleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{19}
}

func (m *SetChatMemberTitleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetChatMemberTitleResponse.Unmarshal(m, b)
}
func (m *SetChatMemberTitleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetChatMemberTitleResponse.Marshal(b, m, deterministic)
}
func (m *SetChatMemberTitleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetChatMemberTitleResponse.Merge(m, src)
}
func (m *SetChatMemberTitleResponse) XXX_Size() int {
	return xxx_messageInfo_SetChatMemberTitleResponse.Size(m)
}
func (m *SetChatMemberTitleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetChatMemberTitleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetChatMemberTitleResponse proto.InternalMessageInfo

type LeaveChatRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveChatRequest) Reset()         { *m = LeaveChatRequest{} }
func (m *LeaveChatRequest) String() string { return proto.CompactTextString(m) }
func (*LeaveChatRequest) ProtoMessage()    {}
func (*LeaveChatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{20}
}

func (m *LeaveChatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveChatRequest.Unmarshal(m, b)
}
func (m *LeaveChatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveChatRequest.Marshal(b, m, deterministic)
}
func (m *LeaveChatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveChatRequest.Merge(m, src)
}
func (m *LeaveChatRequest) XXX_Size() int {
	return xxx_messageInfo_LeaveChatRequest.Size(m)
}
func (m *LeaveChatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveChatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveChatRequest proto.InternalMessageInfo

type LeaveChatResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveChatResponse) Reset()         { *m = LeaveChatResponse{} }
func (m *LeaveChatResponse) String() string { return proto.CompactTextString(m) }
func (*LeaveChatResponse) ProtoMessage()    {}
func (*LeaveChatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{21}
}

func (m *LeaveChatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveChatResponse.Unmarshal(m, b)
}
func (m *LeaveChatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveChatResponse.Marshal(b, m, deterministic)
}
func (m *LeaveChatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveChatResponse.Merge(m, src)
}
func (m *LeaveChatResponse) XXX_Size() int {
	return xxx_messageInfo_LeaveChatResponse.Size(m)
}
func (m *LeaveChatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveChatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveChatResponse proto.InternalMessageInfo

type Message struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	Id                   int64       `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string      `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{22}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_Private
}

func (m *Message) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type SendRequest struct {
	Secret               string     `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Messages             []*Message `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{23}
}

func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (m *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(m, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *SendRequest) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type SendResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResponse) Reset()         { *m = SendResponse{} }
func (m *SendResponse) String() string { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()    {}
func (*SendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{24}
}

func (m *SendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResponse.Unmarshal(m, b)
}
func (m *SendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResponse.Marshal(b, m, deterministic)
}
func (m *SendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResponse.Merge(m, src)
}
func (m *SendResponse) XXX_Size() int {
	return xxx_messageInfo_SendResponse.Size(m)
}
func (m *SendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendResponse proto.InternalMessageInfo

func (m *SendResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type HandleFriendApplicationRequest struct {
	Secret               string   `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Flag                 string   `protobuf:"bytes,2,opt,name=flag,proto3" json:"flag,omitempty"`
	Approve              bool     `protobuf:"varint,3,opt,name=approve,proto3" json:"approve,omitempty"`
	Remark               string   `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleFriendApplicationRequest) Reset()         { *m = HandleFriendApplicationRequest{} }
func (m *HandleFriendApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*HandleFriendApplicationRequest) ProtoMessage()    {}
func (*HandleFriendApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{25}
}

func (m *HandleFriendApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleFriendApplicationRequest.Unmarshal(m, b)
}
func (m *HandleFriendApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleFriendApplicationRequest.Marshal(b, m, deterministic)
}
func (m *HandleFriendApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleFriendApplicationRequest.Merge(m, src)
}
func (m *HandleFriendApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_HandleFriendApplicationRequest.Size(m)
}
func (m *HandleFriendApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleFriendApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleFriendApplicationRequest proto.InternalMessageInfo

func (m *HandleFriendApplicationRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *HandleFriendApplicationRequest) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

func (m *HandleFriendApplicationRequest) GetApprove() bool {
	if m != nil {
		return m.Approve
	}
	return false
}

func (m *HandleFriendApplicationRequest) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

type HandleFriendApplicationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleFriendApplicationResponse) Reset()         { *m = HandleFriendApplicationResponse{} }
func (m *HandleFriendApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*HandleFriendApplicationResponse) ProtoMessage()    {}
func (*HandleFriendApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{26}
}

func (m *HandleFriendApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleFriendApplicationResponse.Unmarshal(m, b)
}
func (m *HandleFriendApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleFriendApplicationResponse.Marshal(b, m, deterministic)
}
func (m *HandleFriendApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleFriendApplicationResponse.Merge(m, src)
}
func (m *HandleFriendApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_HandleFriendApplicationResponse.Size(m)
}
func (m *HandleFriendApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleFriendApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleFriendApplicationResponse proto.InternalMessageInfo

type HandleGroupApplicationRequest struct {
	Secret               string               `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Flag                 string               `protobuf:"bytes,2,opt,name=flag,proto3" json:"flag,omitempty"`
	Type                 GroupApplicationType `protobuf:"varint,3,opt,name=type,proto3,enum=GroupApplicationType" json:"type,omitempty"`
	Approve              bool                 `protobuf:"varint,4,opt,name=approve,proto3" json:"approve,omitempty"`
	Reson                string               `protobuf:"bytes,5,opt,name=reson,proto3" json:"reson,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HandleGroupApplicationRequest) Reset()         { *m = HandleGroupApplicationRequest{} }
func (m *HandleGroupApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*HandleGroupApplicationRequest) ProtoMessage()    {}
func (*HandleGroupApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{27}
}

func (m *HandleGroupApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleGroupApplicationRequest.Unmarshal(m, b)
}
func (m *HandleGroupApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleGroupApplicationRequest.Marshal(b, m, deterministic)
}
func (m *HandleGroupApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleGroupApplicationRequest.Merge(m, src)
}
func (m *HandleGroupApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_HandleGroupApplicationRequest.Size(m)
}
func (m *HandleGroupApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleGroupApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleGroupApplicationRequest proto.InternalMessageInfo

func (m *HandleGroupApplicationRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *HandleGroupApplicationRequest) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

func (m *HandleGroupApplicationRequest) GetType() GroupApplicationType {
	if m != nil {
		return m.Type
	}
	return GroupApplicationType_Add
}

func (m *HandleGroupApplicationRequest) GetApprove() bool {
	if m != nil {
		return m.Approve
	}
	return false
}

func (m *HandleGroupApplicationRequest) GetReson() string {
	if m != nil {
		return m.Reson
	}
	return ""
}

type HandleGroupApplicationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleGroupApplicationResponse) Reset()         { *m = HandleGroupApplicationResponse{} }
func (m *HandleGroupApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*HandleGroupApplicationResponse) ProtoMessage()    {}
func (*HandleGroupApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{28}
}

func (m *HandleGroupApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleGroupApplicationResponse.Unmarshal(m, b)
}
func (m *HandleGroupApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleGroupApplicationResponse.Marshal(b, m, deterministic)
}
func (m *HandleGroupApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleGroupApplicationResponse.Merge(m, src)
}
func (m *HandleGroupApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_HandleGroupApplicationResponse.Size(m)
}
func (m *HandleGroupApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleGroupApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleGroupApplicationResponse proto.InternalMessageInfo

type PluginRegisterRequest struct {
	// bot方加密密钥
	Secret string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	// plugin名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// plugin host
	Host string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	// plugin port
	Port int32 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	// 准备注册的notice事件列表
	NoticeEvents []string `protobuf:"bytes,5,rep,name=notice_events,json=noticeEvents,proto3" json:"notice_events,omitempty"`
	// 准备注册的message事件列表
	MessageEvents []string `protobuf:"bytes,6,rep,name=message_events,json=messageEvents,proto3" json:"message_events,omitempty"`
	// 准备注册的application事件列表
	ApplicationEvents    []string `protobuf:"bytes,7,rep,name=application_events,json=applicationEvents,proto3" json:"application_events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PluginRegisterRequest) Reset()         { *m = PluginRegisterRequest{} }
func (m *PluginRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*PluginRegisterRequest) ProtoMessage()    {}
func (*PluginRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{29}
}

func (m *PluginRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginRegisterRequest.Unmarshal(m, b)
}
func (m *PluginRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginRegisterRequest.Marshal(b, m, deterministic)
}
func (m *PluginRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginRegisterRequest.Merge(m, src)
}
func (m *PluginRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_PluginRegisterRequest.Size(m)
}
func (m *PluginRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PluginRegisterRequest proto.InternalMessageInfo

func (m *PluginRegisterRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *PluginRegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PluginRegisterRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *PluginRegisterRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *PluginRegisterRequest) GetNoticeEvents() []string {
	if m != nil {
		return m.NoticeEvents
	}
	return nil
}

func (m *PluginRegisterRequest) GetMessageEvents() []string {
	if m != nil {
		return m.MessageEvents
	}
	return nil
}

func (m *PluginRegisterRequest) GetApplicationEvents() []string {
	if m != nil {
		return m.ApplicationEvents
	}
	return nil
}

type PluginRegisterResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PluginRegisterResponse) Reset()         { *m = PluginRegisterResponse{} }
func (m *PluginRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*PluginRegisterResponse) ProtoMessage()    {}
func (*PluginRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{30}
}

func (m *PluginRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginRegisterResponse.Unmarshal(m, b)
}
func (m *PluginRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginRegisterResponse.Marshal(b, m, deterministic)
}
func (m *PluginRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginRegisterResponse.Merge(m, src)
}
func (m *PluginRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_PluginRegisterResponse.Size(m)
}
func (m *PluginRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PluginRegisterResponse proto.InternalMessageInfo

func (m *PluginRegisterResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type PluginUnregisterRequest struct {
	// bot方加密密钥
	Secret string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	// plugin名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 准备注销的notice事件列表
	NoticeEvents []string `protobuf:"bytes,3,rep,name=notice_events,json=noticeEvents,proto3" json:"notice_events,omitempty"`
	// 准备注销的message事件列表
	MessageEvents []string `protobuf:"bytes,4,rep,name=message_events,json=messageEvents,proto3" json:"message_events,omitempty"`
	// 准备注销的application事件列表
	ApplicationEvents    []string `protobuf:"bytes,5,rep,name=application_events,json=applicationEvents,proto3" json:"application_events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PluginUnregisterRequest) Reset()         { *m = PluginUnregisterRequest{} }
func (m *PluginUnregisterRequest) String() string { return proto.CompactTextString(m) }
func (*PluginUnregisterRequest) ProtoMessage()    {}
func (*PluginUnregisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{31}
}

func (m *PluginUnregisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginUnregisterRequest.Unmarshal(m, b)
}
func (m *PluginUnregisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginUnregisterRequest.Marshal(b, m, deterministic)
}
func (m *PluginUnregisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginUnregisterRequest.Merge(m, src)
}
func (m *PluginUnregisterRequest) XXX_Size() int {
	return xxx_messageInfo_PluginUnregisterRequest.Size(m)
}
func (m *PluginUnregisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginUnregisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PluginUnregisterRequest proto.InternalMessageInfo

func (m *PluginUnregisterRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *PluginUnregisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PluginUnregisterRequest) GetNoticeEvents() []string {
	if m != nil {
		return m.NoticeEvents
	}
	return nil
}

func (m *PluginUnregisterRequest) GetMessageEvents() []string {
	if m != nil {
		return m.MessageEvents
	}
	return nil
}

func (m *PluginUnregisterRequest) GetApplicationEvents() []string {
	if m != nil {
		return m.ApplicationEvents
	}
	return nil
}

type PluginUnregisterResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PluginUnregisterResponse) Reset()         { *m = PluginUnregisterResponse{} }
func (m *PluginUnregisterResponse) String() string { return proto.CompactTextString(m) }
func (*PluginUnregisterResponse) ProtoMessage()    {}
func (*PluginUnregisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51d7d70385167023, []int{32}
}

func (m *PluginUnregisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginUnregisterResponse.Unmarshal(m, b)
}
func (m *PluginUnregisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginUnregisterResponse.Marshal(b, m, deterministic)
}
func (m *PluginUnregisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginUnregisterResponse.Merge(m, src)
}
func (m *PluginUnregisterResponse) XXX_Size() int {
	return xxx_messageInfo_PluginUnregisterResponse.Size(m)
}
func (m *PluginUnregisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginUnregisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PluginUnregisterResponse proto.InternalMessageInfo

func (m *PluginUnregisterResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterEnum("MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("GroupApplicationType", GroupApplicationType_name, GroupApplicationType_value)
	proto.RegisterType((*DeleteMessageRequest)(nil), "DeleteMessageRequest")
	proto.RegisterType((*DeleteMessageResponse)(nil), "DeleteMessageResponse")
	proto.RegisterType((*LikeRequest)(nil), "LikeRequest")
	proto.RegisterType((*LikeResponse)(nil), "LikeResponse")
	proto.RegisterType((*KickChatMemberRequest)(nil), "KickChatMemberRequest")
	proto.RegisterType((*KickChatMemberResponse)(nil), "KickChatMemberResponse")
	proto.RegisterType((*RestrictChatMemberRequest)(nil), "RestrictChatMemberRequest")
	proto.RegisterType((*RestrictChatMemberResponse)(nil), "RestrictChatMemberResponse")
	proto.RegisterType((*RestrictAnonymousChatMemberRequest)(nil), "RestrictAnonymousChatMemberRequest")
	proto.RegisterType((*RestrictAnonymousChatMemberResponse)(nil), "RestrictAnonymousChatMemberResponse")
	proto.RegisterType((*RestrictAllChatMembersRequest)(nil), "RestrictAllChatMembersRequest")
	proto.RegisterType((*RestrictAllChatMembersResponse)(nil), "RestrictAllChatMembersResponse")
	proto.RegisterType((*PromoteChatMemberRequest)(nil), "PromoteChatMemberRequest")
	proto.RegisterType((*PromoteChatMemberResponse)(nil), "PromoteChatMemberResponse")
	proto.RegisterType((*EnableAnonymousChatRequest)(nil), "EnableAnonymousChatRequest")
	proto.RegisterType((*EnableAnonymousChatResponse)(nil), "EnableAnonymousChatResponse")
	proto.RegisterType((*SetChatMemberCardRequest)(nil), "SetChatMemberCardRequest")
	proto.RegisterType((*SetChatMemberCardResponse)(nil), "SetChatMemberCardResponse")
	proto.RegisterType((*SetChatMemberTitleRequest)(nil), "SetChatMemberTitleRequest")
	proto.RegisterType((*SetChatMemberTitleResponse)(nil), "SetChatMemberTitleResponse")
	proto.RegisterType((*LeaveChatRequest)(nil), "LeaveChatRequest")
	proto.RegisterType((*LeaveChatResponse)(nil), "LeaveChatResponse")
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*SendRequest)(nil), "SendRequest")
	proto.RegisterType((*SendResponse)(nil), "SendResponse")
	proto.RegisterType((*HandleFriendApplicationRequest)(nil), "HandleFriendApplicationRequest")
	proto.RegisterType((*HandleFriendApplicationResponse)(nil), "HandleFriendApplicationResponse")
	proto.RegisterType((*HandleGroupApplicationRequest)(nil), "HandleGroupApplicationRequest")
	proto.RegisterType((*HandleGroupApplicationResponse)(nil), "HandleGroupApplicationResponse")
	proto.RegisterType((*PluginRegisterRequest)(nil), "PluginRegisterRequest")
	proto.RegisterType((*PluginRegisterResponse)(nil), "PluginRegisterResponse")
	proto.RegisterType((*PluginUnregisterRequest)(nil), "PluginUnregisterRequest")
	proto.RegisterType((*PluginUnregisterResponse)(nil), "PluginUnregisterResponse")
}

func init() { proto.RegisterFile("bot.proto", fileDescriptor_51d7d70385167023) }

var fileDescriptor_51d7d70385167023 = []byte{
	// 797 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x8e, 0xda, 0x46,
	0x14, 0xc6, 0x98, 0xdf, 0xc3, 0x8f, 0xc8, 0x74, 0x01, 0xaf, 0x37, 0x2c, 0xd4, 0xc9, 0x56, 0x34,
	0x55, 0xad, 0x8a, 0xaa, 0x0f, 0xb0, 0xdd, 0xa4, 0xed, 0x2a, 0x89, 0xba, 0x72, 0xd2, 0xab, 0x4a,
	0x8d, 0x0c, 0x3e, 0x25, 0xa3, 0x35, 0x1e, 0xd7, 0x33, 0xa0, 0xee, 0x4d, 0x1f, 0xa7, 0xcf, 0xd1,
	0xa7, 0xe9, 0x3b, 0xf4, 0xae, 0xf2, 0x78, 0x0c, 0x06, 0x0c, 0x44, 0xda, 0xbb, 0x99, 0xf3, 0x7d,
	0xe7, 0xf3, 0xf9, 0x66, 0xce, 0x19, 0x19, 0xea, 0x53, 0x26, 0xec, 0x30, 0x62, 0x82, 0x59, 0xdf,
	0xc1, 0xd9, 0x4b, 0xf4, 0x51, 0xe0, 0x5b, 0xe4, 0xdc, 0x9d, 0xa3, 0x83, 0x7f, 0x2c, 0x91, 0x0b,
	0x32, 0x00, 0x58, 0x24, 0x91, 0x0f, 0xd4, 0x33, 0xb4, 0x91, 0x36, 0xd6, 0x9d, 0xba, 0x8a, 0xdc,
	0x7a, 0x56, 0x1f, 0xba, 0x3b, 0x69, 0x3c, 0x64, 0x01, 0x47, 0xab, 0x05, 0x8d, 0x37, 0xf4, 0x3e,
	0x95, 0xb1, 0xda, 0xd0, 0x4c, 0xb6, 0x0a, 0xee, 0x43, 0xf7, 0x35, 0x9d, 0xdd, 0xdf, 0x7c, 0x74,
	0xc5, 0x5b, 0x5c, 0x4c, 0x31, 0x4a, 0x89, 0x06, 0xf4, 0x76, 0x01, 0x95, 0x72, 0x01, 0xe7, 0x0e,
	0x72, 0x11, 0xd1, 0x99, 0xd8, 0x4f, 0x7b, 0x0a, 0x66, 0x1e, 0xa8, 0x52, 0x9f, 0x83, 0x95, 0xa2,
	0xd7, 0x01, 0x0b, 0x1e, 0x16, 0x6c, 0xc9, 0xf7, 0x35, 0xae, 0xe0, 0xd9, 0x51, 0x96, 0x12, 0x1b,
	0xc2, 0x60, 0x4d, 0xf3, 0xfd, 0x0d, 0x81, 0xa7, 0x3a, 0x23, 0xb8, 0x3c, 0x44, 0x50, 0x12, 0x26,
	0x18, 0x77, 0x11, 0x5b, 0x30, 0x81, 0xfb, 0x55, 0x5c, 0xc0, 0x79, 0x0e, 0xa6, 0x12, 0x9f, 0x82,
	0xf9, 0x2a, 0x70, 0xa7, 0x3e, 0x6e, 0x15, 0x98, 0xa6, 0x0e, 0xe0, 0x22, 0x17, 0xdd, 0x7c, 0xf5,
	0x1d, 0x66, 0x8e, 0xe7, 0xc6, 0x8d, 0xbc, 0xcc, 0x57, 0x73, 0xb0, 0xcd, 0xc9, 0x6f, 0x81, 0xef,
	0xa9, 0xf0, 0x31, 0x73, 0xf2, 0x79, 0xa0, 0x4a, 0x25, 0xd0, 0x79, 0x83, 0xee, 0x0a, 0xb3, 0x65,
	0x7e, 0x06, 0x4f, 0x32, 0x31, 0x45, 0xfc, 0x19, 0xaa, 0xaa, 0x85, 0xc8, 0x08, 0x4a, 0xe2, 0x21,
	0x44, 0xd9, 0x6c, 0xed, 0x49, 0xd3, 0x56, 0xf1, 0xf7, 0x0f, 0x21, 0x3a, 0x12, 0x21, 0x6d, 0x28,
	0x52, 0xcf, 0x28, 0xca, 0x66, 0x2c, 0x52, 0x8f, 0x10, 0x28, 0x09, 0xfc, 0x53, 0x18, 0xfa, 0x48,
	0x1b, 0xd7, 0x1d, 0xb9, 0xb6, 0x5e, 0x43, 0xe3, 0x1d, 0x06, 0xa9, 0x41, 0xd2, 0x83, 0x0a, 0xc7,
	0x59, 0x84, 0x42, 0xca, 0xd6, 0x1d, 0xb5, 0x23, 0xcf, 0xa1, 0xa6, 0xba, 0x99, 0x1b, 0xc5, 0x91,
	0x3e, 0x6e, 0x4c, 0x6a, 0xe9, 0x07, 0x9d, 0x35, 0x62, 0x7d, 0x01, 0xcd, 0x44, 0x2c, 0xa9, 0x56,
	0xaa, 0x09, 0x57, 0x2c, 0xb9, 0x54, 0xab, 0x39, 0x6a, 0x67, 0xfd, 0x05, 0x97, 0x3f, 0xb9, 0x81,
	0xe7, 0xe3, 0x0f, 0x11, 0xc5, 0xc0, 0xbb, 0x0e, 0x43, 0x9f, 0xce, 0x5c, 0x41, 0x59, 0x70, 0xaa,
	0x0e, 0x02, 0xa5, 0xdf, 0x7d, 0x77, 0x2e, 0x4d, 0xd5, 0x1d, 0xb9, 0x26, 0x06, 0x54, 0xdd, 0x30,
	0x8c, 0xd8, 0x0a, 0xa5, 0xb3, 0x9a, 0x93, 0x6e, 0x63, 0x95, 0x08, 0x17, 0x6e, 0x74, 0x6f, 0x94,
	0x12, 0x95, 0x64, 0x67, 0x7d, 0x0e, 0xc3, 0x83, 0xdf, 0x57, 0x07, 0xfd, 0xb7, 0x06, 0x83, 0x84,
	0xf3, 0x63, 0xc4, 0x96, 0xe1, 0x23, 0x4b, 0xfc, 0x52, 0xdd, 0x95, 0x2e, 0xef, 0xaa, 0x6b, 0xef,
	0x6a, 0x66, 0x2e, 0x2d, 0xe3, 0xa6, 0xb4, 0xed, 0xe6, 0x0c, 0xca, 0x11, 0x72, 0x16, 0x18, 0x65,
	0xa9, 0x9c, 0x6c, 0xe2, 0x31, 0x3a, 0x54, 0xa7, 0xb2, 0xf2, 0xaf, 0x06, 0xdd, 0x3b, 0x7f, 0x39,
	0xa7, 0x81, 0x83, 0x73, 0xca, 0xc5, 0x7a, 0x88, 0x8e, 0x59, 0x08, 0xdc, 0x05, 0xa6, 0x16, 0xe2,
	0x75, 0x1c, 0xfb, 0xc8, 0xf8, 0xba, 0x79, 0xe2, 0x75, 0x1c, 0x0b, 0x59, 0x24, 0x64, 0xa1, 0x65,
	0x47, 0xae, 0xc9, 0x33, 0x68, 0x05, 0x4c, 0xd0, 0x19, 0x7e, 0xc0, 0x15, 0x06, 0x82, 0x1b, 0xe5,
	0x91, 0x3e, 0xae, 0x3b, 0xcd, 0x24, 0xf8, 0x4a, 0xc6, 0xc8, 0x15, 0xb4, 0xd3, 0xe7, 0x52, 0xb1,
	0x2a, 0x92, 0xd5, 0x52, 0x51, 0x45, 0xfb, 0x1a, 0x88, 0xbb, 0x31, 0x94, 0x52, 0xab, 0x92, 0xfa,
	0x24, 0x83, 0x24, 0x74, 0xeb, 0x1b, 0xe8, 0xed, 0xfa, 0x3c, 0xd1, 0x88, 0xff, 0x68, 0xd0, 0x4f,
	0x52, 0x7e, 0x09, 0xa2, 0x47, 0x1c, 0xce, 0x9e, 0x69, 0xfd, 0x93, 0x4c, 0x97, 0x3e, 0xdd, 0x74,
	0xf9, 0x90, 0xe9, 0x09, 0x18, 0xfb, 0x0e, 0x8e, 0xdb, 0x7e, 0x31, 0x81, 0x46, 0xe6, 0xb5, 0x20,
	0x0d, 0xa8, 0xde, 0x45, 0x74, 0xe5, 0x0a, 0xec, 0x14, 0x48, 0x1d, 0xca, 0xb2, 0x93, 0x3a, 0x5a,
	0x1c, 0x7f, 0x49, 0xf9, 0x6c, 0xc9, 0x79, 0xa7, 0xf8, 0xe2, 0x2b, 0x38, 0xcb, 0xeb, 0x5a, 0x52,
	0x05, 0xfd, 0xda, 0xf3, 0x3a, 0x05, 0x02, 0x50, 0xb9, 0x0d, 0x56, 0x54, 0x60, 0x47, 0x9b, 0xfc,
	0x57, 0x04, 0xfd, 0x7b, 0x26, 0xc8, 0x15, 0x94, 0xe2, 0x07, 0x81, 0x34, 0xed, 0xcc, 0x23, 0x63,
	0xb6, 0xec, 0xec, 0x2b, 0x61, 0x15, 0xc8, 0x6f, 0xd0, 0x3f, 0x30, 0x8f, 0x64, 0x68, 0x1f, 0x7f,
	0x29, 0xcc, 0x91, 0x7d, 0x6a, 0x94, 0x0b, 0xe4, 0x57, 0xe8, 0xe5, 0xcf, 0x08, 0xb9, 0xb4, 0x8f,
	0x0e, 0xb9, 0x39, 0xb4, 0x4f, 0x0c, 0x57, 0x81, 0xdc, 0x40, 0x7b, 0xbb, 0xeb, 0x48, 0xcf, 0xce,
	0x1d, 0x37, 0xb3, 0x6f, 0xe7, 0xb7, 0xa7, 0x55, 0x20, 0xb7, 0xd0, 0xd9, 0xbd, 0x45, 0x62, 0xd8,
	0x07, 0x5a, 0xd3, 0x3c, 0xb7, 0x0f, 0x5d, 0xb9, 0x55, 0x98, 0x56, 0xe4, 0x9f, 0xca, 0xb7, 0xff,
	0x07, 0x00, 0x00, 0xff, 0xff, 0x91, 0xc8, 0x6d, 0x25, 0xb6, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BotClient is the client API for Bot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BotClient interface {
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	HandleFriendApplication(ctx context.Context, in *HandleFriendApplicationRequest, opts ...grpc.CallOption) (*HandleFriendApplicationResponse, error)
	HandleGroupApplication(ctx context.Context, in *HandleGroupApplicationRequest, opts ...grpc.CallOption) (*HandleGroupApplicationResponse, error)
	//    rpc DeleteMessage(DeleteMessageRequest)returns(DeleteMessageResponse){};
	//    rpc Like(LikeRequest)returns(LikeResponse){};
	//    rpc KickChatMember(KickChatMemberRequest)returns(KickChatMemberResponse){};
	//    rpc RestrictChatMember(RestrictChatMemberRequest)returns(RestrictChatMemberResponse){};
	//    rpc RestrictAnonymousChatMember(RestrictAnonymousChatMemberRequest)returns(RestrictAnonymousChatMemberResponse){};
	//    rpc RestrictAllChatMembers(RestrictAllChatMembersRequest)returns(RestrictAllChatMembersResponse){};
	//    rpc PromoteChatMember(PromoteChatMemberRequest)returns(PromoteChatMemberResponse){};
	//    rpc EnableAnonymousChat(EnableAnonymousChatRequest)returns(EnableAnonymousChatResponse){};
	//    rpc SetChatMemberCard(SetChatMemberCardRequest)returns(SetChatMemberCardResponse){};
	//    rpc SetChatMemberTitle(SetChatMemberTitleRequest)returns(SetChatMemberTitleResponse){};
	//    rpc LeaveChat(LeaveChatRequest)returns(LeaveChatResponse){};
	PluginRegister(ctx context.Context, in *PluginRegisterRequest, opts ...grpc.CallOption) (*PluginRegisterResponse, error)
	PluginUnregister(ctx context.Context, in *PluginUnregisterRequest, opts ...grpc.CallOption) (*PluginUnregisterResponse, error)
}

type botClient struct {
	cc *grpc.ClientConn
}

func NewBotClient(cc *grpc.ClientConn) BotClient {
	return &botClient{cc}
}

func (c *botClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, "/Bot/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) HandleFriendApplication(ctx context.Context, in *HandleFriendApplicationRequest, opts ...grpc.CallOption) (*HandleFriendApplicationResponse, error) {
	out := new(HandleFriendApplicationResponse)
	err := c.cc.Invoke(ctx, "/Bot/HandleFriendApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) HandleGroupApplication(ctx context.Context, in *HandleGroupApplicationRequest, opts ...grpc.CallOption) (*HandleGroupApplicationResponse, error) {
	out := new(HandleGroupApplicationResponse)
	err := c.cc.Invoke(ctx, "/Bot/HandleGroupApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) PluginRegister(ctx context.Context, in *PluginRegisterRequest, opts ...grpc.CallOption) (*PluginRegisterResponse, error) {
	out := new(PluginRegisterResponse)
	err := c.cc.Invoke(ctx, "/Bot/PluginRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) PluginUnregister(ctx context.Context, in *PluginUnregisterRequest, opts ...grpc.CallOption) (*PluginUnregisterResponse, error) {
	out := new(PluginUnregisterResponse)
	err := c.cc.Invoke(ctx, "/Bot/PluginUnregister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotServer is the server API for Bot service.
type BotServer interface {
	Send(context.Context, *SendRequest) (*SendResponse, error)
	HandleFriendApplication(context.Context, *HandleFriendApplicationRequest) (*HandleFriendApplicationResponse, error)
	HandleGroupApplication(context.Context, *HandleGroupApplicationRequest) (*HandleGroupApplicationResponse, error)
	//    rpc DeleteMessage(DeleteMessageRequest)returns(DeleteMessageResponse){};
	//    rpc Like(LikeRequest)returns(LikeResponse){};
	//    rpc KickChatMember(KickChatMemberRequest)returns(KickChatMemberResponse){};
	//    rpc RestrictChatMember(RestrictChatMemberRequest)returns(RestrictChatMemberResponse){};
	//    rpc RestrictAnonymousChatMember(RestrictAnonymousChatMemberRequest)returns(RestrictAnonymousChatMemberResponse){};
	//    rpc RestrictAllChatMembers(RestrictAllChatMembersRequest)returns(RestrictAllChatMembersResponse){};
	//    rpc PromoteChatMember(PromoteChatMemberRequest)returns(PromoteChatMemberResponse){};
	//    rpc EnableAnonymousChat(EnableAnonymousChatRequest)returns(EnableAnonymousChatResponse){};
	//    rpc SetChatMemberCard(SetChatMemberCardRequest)returns(SetChatMemberCardResponse){};
	//    rpc SetChatMemberTitle(SetChatMemberTitleRequest)returns(SetChatMemberTitleResponse){};
	//    rpc LeaveChat(LeaveChatRequest)returns(LeaveChatResponse){};
	PluginRegister(context.Context, *PluginRegisterRequest) (*PluginRegisterResponse, error)
	PluginUnregister(context.Context, *PluginUnregisterRequest) (*PluginUnregisterResponse, error)
}

// UnimplementedBotServer can be embedded to have forward compatible implementations.
type UnimplementedBotServer struct {
}

func (*UnimplementedBotServer) Send(ctx context.Context, req *SendRequest) (*SendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedBotServer) HandleFriendApplication(ctx context.Context, req *HandleFriendApplicationRequest) (*HandleFriendApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleFriendApplication not implemented")
}
func (*UnimplementedBotServer) HandleGroupApplication(ctx context.Context, req *HandleGroupApplicationRequest) (*HandleGroupApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleGroupApplication not implemented")
}
func (*UnimplementedBotServer) PluginRegister(ctx context.Context, req *PluginRegisterRequest) (*PluginRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginRegister not implemented")
}
func (*UnimplementedBotServer) PluginUnregister(ctx context.Context, req *PluginUnregisterRequest) (*PluginUnregisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginUnregister not implemented")
}

func RegisterBotServer(s *grpc.Server, srv BotServer) {
	s.RegisterService(&_Bot_serviceDesc, srv)
}

func _Bot_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Bot/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_HandleFriendApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleFriendApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).HandleFriendApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Bot/HandleFriendApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).HandleFriendApplication(ctx, req.(*HandleFriendApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_HandleGroupApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleGroupApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).HandleGroupApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Bot/HandleGroupApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).HandleGroupApplication(ctx, req.(*HandleGroupApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_PluginRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).PluginRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Bot/PluginRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).PluginRegister(ctx, req.(*PluginRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_PluginUnregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginUnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).PluginUnregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Bot/PluginUnregister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).PluginUnregister(ctx, req.(*PluginUnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Bot",
	HandlerType: (*BotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Bot_Send_Handler,
		},
		{
			MethodName: "HandleFriendApplication",
			Handler:    _Bot_HandleFriendApplication_Handler,
		},
		{
			MethodName: "HandleGroupApplication",
			Handler:    _Bot_HandleGroupApplication_Handler,
		},
		{
			MethodName: "PluginRegister",
			Handler:    _Bot_PluginRegister_Handler,
		},
		{
			MethodName: "PluginUnregister",
			Handler:    _Bot_PluginUnregister_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bot.proto",
}
