// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

package plugin

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type_UnknownChat Type = 0
	Type_PrivateChat Type = 1
	Type_GroupChat   Type = 2
	Type_DiscussChat Type = 3
)

var Type_name = map[int32]string{
	0: "UnknownChat",
	1: "PrivateChat",
	2: "GroupChat",
	3: "DiscussChat",
}

var Type_value = map[string]int32{
	"UnknownChat": 0,
	"PrivateChat": 1,
	"GroupChat":   2,
	"DiscussChat": 3,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{0}
}

type SubType int32

const (
	// Private
	SubType_Other   SubType = 0
	SubType_Friend  SubType = 1
	SubType_Group   SubType = 2
	SubType_Discuss SubType = 3
	// Group
	SubType_Normal    SubType = 4
	SubType_Anonymous SubType = 5
	SubType_Notice    SubType = 6
)

var SubType_name = map[int32]string{
	0: "Other",
	1: "Friend",
	2: "Group",
	3: "Discuss",
	4: "Normal",
	5: "Anonymous",
	6: "Notice",
}

var SubType_value = map[string]int32{
	"Other":     0,
	"Friend":    1,
	"Group":     2,
	"Discuss":   3,
	"Normal":    4,
	"Anonymous": 5,
	"Notice":    6,
}

func (x SubType) String() string {
	return proto.EnumName(SubType_name, int32(x))
}

func (SubType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{1}
}

type ApplicationType int32

const (
	ApplicationType_FriendAdd   ApplicationType = 0
	ApplicationType_GroupAdd    ApplicationType = 1
	ApplicationType_GroupInvite ApplicationType = 2
)

var ApplicationType_name = map[int32]string{
	0: "FriendAdd",
	1: "GroupAdd",
	2: "GroupInvite",
}

var ApplicationType_value = map[string]int32{
	"FriendAdd":   0,
	"GroupAdd":    1,
	"GroupInvite": 2,
}

func (x ApplicationType) String() string {
	return proto.EnumName(ApplicationType_name, int32(x))
}

func (ApplicationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{2}
}

type Sender struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Sex                  string   `protobuf:"bytes,3,opt,name=sex,proto3" json:"sex,omitempty"`
	Age                  int32    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sender) Reset()         { *m = Sender{} }
func (m *Sender) String() string { return proto.CompactTextString(m) }
func (*Sender) ProtoMessage()    {}
func (*Sender) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{0}
}

func (m *Sender) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sender.Unmarshal(m, b)
}
func (m *Sender) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sender.Marshal(b, m, deterministic)
}
func (m *Sender) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sender.Merge(m, src)
}
func (m *Sender) XXX_Size() int {
	return xxx_messageInfo_Sender.Size(m)
}
func (m *Sender) XXX_DiscardUnknown() {
	xxx_messageInfo_Sender.DiscardUnknown(m)
}

var xxx_messageInfo_Sender proto.InternalMessageInfo

func (m *Sender) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Sender) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Sender) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *Sender) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type HandleMessageRequest struct {
	Bot                  int64    `protobuf:"varint,1,opt,name=bot,proto3" json:"bot,omitempty"`
	Time                 int64    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	MessageId            int64    `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Type                 Type     `protobuf:"varint,4,opt,name=type,proto3,enum=Type" json:"type,omitempty"`
	SubType              SubType  `protobuf:"varint,5,opt,name=sub_type,json=subType,proto3,enum=SubType" json:"sub_type,omitempty"`
	UserId               int64    `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId              int64    `protobuf:"varint,7,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	DiscussId            int64    `protobuf:"varint,8,opt,name=discuss_id,json=discussId,proto3" json:"discuss_id,omitempty"`
	Text                 string   `protobuf:"bytes,9,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleMessageRequest) Reset()         { *m = HandleMessageRequest{} }
func (m *HandleMessageRequest) String() string { return proto.CompactTextString(m) }
func (*HandleMessageRequest) ProtoMessage()    {}
func (*HandleMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{1}
}

func (m *HandleMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleMessageRequest.Unmarshal(m, b)
}
func (m *HandleMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleMessageRequest.Marshal(b, m, deterministic)
}
func (m *HandleMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleMessageRequest.Merge(m, src)
}
func (m *HandleMessageRequest) XXX_Size() int {
	return xxx_messageInfo_HandleMessageRequest.Size(m)
}
func (m *HandleMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleMessageRequest proto.InternalMessageInfo

func (m *HandleMessageRequest) GetBot() int64 {
	if m != nil {
		return m.Bot
	}
	return 0
}

func (m *HandleMessageRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *HandleMessageRequest) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *HandleMessageRequest) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_UnknownChat
}

func (m *HandleMessageRequest) GetSubType() SubType {
	if m != nil {
		return m.SubType
	}
	return SubType_Other
}

func (m *HandleMessageRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *HandleMessageRequest) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *HandleMessageRequest) GetDiscussId() int64 {
	if m != nil {
		return m.DiscussId
	}
	return 0
}

func (m *HandleMessageRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type HandleMessageResponse struct {
	Reply                string   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	AtSender             bool     `protobuf:"varint,2,opt,name=at_sender,json=atSender,proto3" json:"at_sender,omitempty"`
	AutoEscape           bool     `protobuf:"varint,3,opt,name=auto_escape,json=autoEscape,proto3" json:"auto_escape,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleMessageResponse) Reset()         { *m = HandleMessageResponse{} }
func (m *HandleMessageResponse) String() string { return proto.CompactTextString(m) }
func (*HandleMessageResponse) ProtoMessage()    {}
func (*HandleMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{2}
}

func (m *HandleMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleMessageResponse.Unmarshal(m, b)
}
func (m *HandleMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleMessageResponse.Marshal(b, m, deterministic)
}
func (m *HandleMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleMessageResponse.Merge(m, src)
}
func (m *HandleMessageResponse) XXX_Size() int {
	return xxx_messageInfo_HandleMessageResponse.Size(m)
}
func (m *HandleMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleMessageResponse proto.InternalMessageInfo

func (m *HandleMessageResponse) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func (m *HandleMessageResponse) GetAtSender() bool {
	if m != nil {
		return m.AtSender
	}
	return false
}

func (m *HandleMessageResponse) GetAutoEscape() bool {
	if m != nil {
		return m.AutoEscape
	}
	return false
}

type HandleApplicationRequest struct {
	Type                 ApplicationType `protobuf:"varint,1,opt,name=type,proto3,enum=ApplicationType" json:"type,omitempty"`
	UserId               int64           `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId              int64           `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Comment              string          `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Flag                 string          `protobuf:"bytes,5,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HandleApplicationRequest) Reset()         { *m = HandleApplicationRequest{} }
func (m *HandleApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*HandleApplicationRequest) ProtoMessage()    {}
func (*HandleApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{3}
}

func (m *HandleApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleApplicationRequest.Unmarshal(m, b)
}
func (m *HandleApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleApplicationRequest.Marshal(b, m, deterministic)
}
func (m *HandleApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleApplicationRequest.Merge(m, src)
}
func (m *HandleApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_HandleApplicationRequest.Size(m)
}
func (m *HandleApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleApplicationRequest proto.InternalMessageInfo

func (m *HandleApplicationRequest) GetType() ApplicationType {
	if m != nil {
		return m.Type
	}
	return ApplicationType_FriendAdd
}

func (m *HandleApplicationRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *HandleApplicationRequest) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *HandleApplicationRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *HandleApplicationRequest) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

type HandleApplicationResponse struct {
	Approve              bool     `protobuf:"varint,1,opt,name=approve,proto3" json:"approve,omitempty"`
	Remark               string   `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Reason               string   `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleApplicationResponse) Reset()         { *m = HandleApplicationResponse{} }
func (m *HandleApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*HandleApplicationResponse) ProtoMessage()    {}
func (*HandleApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{4}
}

func (m *HandleApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleApplicationResponse.Unmarshal(m, b)
}
func (m *HandleApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleApplicationResponse.Marshal(b, m, deterministic)
}
func (m *HandleApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleApplicationResponse.Merge(m, src)
}
func (m *HandleApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_HandleApplicationResponse.Size(m)
}
func (m *HandleApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleApplicationResponse proto.InternalMessageInfo

func (m *HandleApplicationResponse) GetApprove() bool {
	if m != nil {
		return m.Approve
	}
	return false
}

func (m *HandleApplicationResponse) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *HandleApplicationResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type HandleNoticeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleNoticeRequest) Reset()         { *m = HandleNoticeRequest{} }
func (m *HandleNoticeRequest) String() string { return proto.CompactTextString(m) }
func (*HandleNoticeRequest) ProtoMessage()    {}
func (*HandleNoticeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{5}
}

func (m *HandleNoticeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleNoticeRequest.Unmarshal(m, b)
}
func (m *HandleNoticeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleNoticeRequest.Marshal(b, m, deterministic)
}
func (m *HandleNoticeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleNoticeRequest.Merge(m, src)
}
func (m *HandleNoticeRequest) XXX_Size() int {
	return xxx_messageInfo_HandleNoticeRequest.Size(m)
}
func (m *HandleNoticeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleNoticeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleNoticeRequest proto.InternalMessageInfo

type HandleNoticeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleNoticeResponse) Reset()         { *m = HandleNoticeResponse{} }
func (m *HandleNoticeResponse) String() string { return proto.CompactTextString(m) }
func (*HandleNoticeResponse) ProtoMessage()    {}
func (*HandleNoticeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{6}
}

func (m *HandleNoticeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleNoticeResponse.Unmarshal(m, b)
}
func (m *HandleNoticeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleNoticeResponse.Marshal(b, m, deterministic)
}
func (m *HandleNoticeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleNoticeResponse.Merge(m, src)
}
func (m *HandleNoticeResponse) XXX_Size() int {
	return xxx_messageInfo_HandleNoticeResponse.Size(m)
}
func (m *HandleNoticeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleNoticeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleNoticeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("Type", Type_name, Type_value)
	proto.RegisterEnum("SubType", SubType_name, SubType_value)
	proto.RegisterEnum("ApplicationType", ApplicationType_name, ApplicationType_value)
	proto.RegisterType((*Sender)(nil), "Sender")
	proto.RegisterType((*HandleMessageRequest)(nil), "HandleMessageRequest")
	proto.RegisterType((*HandleMessageResponse)(nil), "HandleMessageResponse")
	proto.RegisterType((*HandleApplicationRequest)(nil), "HandleApplicationRequest")
	proto.RegisterType((*HandleApplicationResponse)(nil), "HandleApplicationResponse")
	proto.RegisterType((*HandleNoticeRequest)(nil), "HandleNoticeRequest")
	proto.RegisterType((*HandleNoticeResponse)(nil), "HandleNoticeResponse")
}

func init() { proto.RegisterFile("plugin.proto", fileDescriptor_22a625af4bc1cc87) }

var fileDescriptor_22a625af4bc1cc87 = []byte{
	// 644 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0xed, 0xc4, 0x1f, 0xd3, 0x2f, 0xb3, 0x34, 0xc5, 0x0d, 0x42, 0x54, 0x86, 0x43, 0xd5,
	0x83, 0x0f, 0xe5, 0x8c, 0xa0, 0xe2, 0xab, 0x91, 0xa0, 0x54, 0x2e, 0x48, 0xdc, 0xa2, 0x4d, 0xbc,
	0xa4, 0x56, 0xe2, 0x5d, 0xe3, 0x5d, 0x97, 0xe6, 0xca, 0x4f, 0xe1, 0x4f, 0xf1, 0x77, 0xd0, 0xce,
	0x6e, 0x50, 0x5a, 0x92, 0xdb, 0xbc, 0x37, 0xeb, 0x9d, 0xf1, 0x7b, 0xcf, 0x86, 0xed, 0x7a, 0xde,
	0x4e, 0x4b, 0x9e, 0xd5, 0x8d, 0x50, 0x22, 0xfd, 0x06, 0xfe, 0x15, 0xe3, 0x05, 0x6b, 0xc8, 0x2e,
	0xb8, 0x65, 0x91, 0x38, 0x47, 0xce, 0xb1, 0x97, 0xbb, 0x65, 0x41, 0x06, 0x10, 0xf2, 0x72, 0x32,
	0xe3, 0xb4, 0x62, 0x89, 0x7b, 0xe4, 0x1c, 0x47, 0xf9, 0x3f, 0x4c, 0x62, 0xf0, 0x24, 0xbb, 0x4d,
	0x3c, 0xa4, 0x75, 0xa9, 0x19, 0x3a, 0x65, 0x49, 0xf7, 0xc8, 0x39, 0xee, 0xe5, 0xba, 0x4c, 0x7f,
	0xb9, 0xb0, 0x7f, 0x4e, 0x79, 0x31, 0x67, 0x9f, 0x98, 0x94, 0x74, 0xca, 0x72, 0xf6, 0xa3, 0x65,
	0x52, 0xe9, 0xa3, 0x63, 0xa1, 0xec, 0x24, 0x5d, 0x12, 0x02, 0x5d, 0x55, 0xda, 0x31, 0x5e, 0x8e,
	0x35, 0x79, 0x02, 0x50, 0x99, 0xe7, 0x46, 0x65, 0x81, 0x93, 0xbc, 0x3c, 0xb2, 0xcc, 0xb0, 0x20,
	0x87, 0xd0, 0x55, 0x8b, 0xda, 0x0c, 0xdc, 0x3d, 0xed, 0x65, 0x5f, 0x16, 0x35, 0xcb, 0x91, 0x22,
	0xcf, 0x20, 0x94, 0xed, 0x78, 0x84, 0xed, 0x1e, 0xb6, 0xc3, 0xec, 0xaa, 0x1d, 0xe3, 0x89, 0x40,
	0x9a, 0x82, 0x3c, 0x82, 0xa0, 0x95, 0xac, 0xd1, 0x77, 0xfb, 0x78, 0xb7, 0xaf, 0x21, 0x5e, 0x1c,
	0x4e, 0x1b, 0xd1, 0xd6, 0xba, 0x13, 0x60, 0x27, 0x40, 0x3c, 0x2c, 0xf4, 0x4a, 0x45, 0x29, 0x27,
	0xad, 0x94, 0xba, 0x19, 0x9a, 0x95, 0x2c, 0x33, 0x2c, 0xf0, 0x2d, 0xd8, 0xad, 0x4a, 0x22, 0x54,
	0x05, 0xeb, 0x74, 0x06, 0xfd, 0x7b, 0x1a, 0xc8, 0x5a, 0x70, 0xc9, 0xc8, 0x3e, 0xf4, 0x1a, 0x56,
	0xcf, 0x17, 0x28, 0x43, 0x94, 0x1b, 0x40, 0x1e, 0x43, 0x44, 0xd5, 0x48, 0xa2, 0x21, 0xa8, 0x46,
	0x98, 0x87, 0x54, 0x59, 0x83, 0x9e, 0xc2, 0x16, 0x6d, 0x95, 0x18, 0x31, 0x39, 0xa1, 0x35, 0x43,
	0x49, 0xc2, 0x1c, 0x34, 0xf5, 0x0e, 0x99, 0xf4, 0xb7, 0x03, 0x89, 0x99, 0x76, 0x56, 0xd7, 0xf3,
	0x72, 0x42, 0x55, 0x29, 0xf8, 0x52, 0xf5, 0xe7, 0x56, 0x30, 0x07, 0x15, 0x89, 0xb3, 0x95, 0x23,
	0x2b, 0xda, 0xad, 0xc8, 0xe2, 0x6e, 0x94, 0xc5, 0xbb, 0x2b, 0x4b, 0x02, 0xc1, 0x44, 0x54, 0x15,
	0xe3, 0x0a, 0xdd, 0x88, 0xf2, 0x25, 0xd4, 0x8a, 0x7c, 0x9f, 0xd3, 0x29, 0xba, 0x10, 0xe5, 0x58,
	0xa7, 0x0c, 0x0e, 0xd7, 0xec, 0x68, 0x55, 0x49, 0x20, 0xa0, 0x75, 0xdd, 0x88, 0x1b, 0xb3, 0x67,
	0x98, 0x2f, 0x21, 0x39, 0x00, 0xbf, 0x61, 0x15, 0x6d, 0x66, 0x36, 0x8b, 0x16, 0x19, 0x9e, 0x4a,
	0xc1, 0x6d, 0x18, 0x2d, 0x4a, 0xfb, 0xf0, 0xd0, 0x8c, 0xb9, 0x10, 0xaa, 0x9c, 0x2c, 0xb3, 0x97,
	0x1e, 0x2c, 0x33, 0xb9, 0xa4, 0xcd, 0xe0, 0x93, 0x73, 0xe8, 0x62, 0x2c, 0xf6, 0x60, 0xeb, 0x2b,
	0x9f, 0x71, 0xf1, 0x93, 0xbf, 0xb9, 0xa6, 0x2a, 0xee, 0x68, 0xe2, 0xb2, 0x29, 0x6f, 0xa8, 0x62,
	0x48, 0x38, 0x64, 0x07, 0xa2, 0x0f, 0xfa, 0xc5, 0x11, 0xba, 0xba, 0xff, 0xd6, 0x24, 0x00, 0x09,
	0xef, 0x64, 0x04, 0x81, 0x0d, 0x1b, 0x89, 0xa0, 0xf7, 0x59, 0x5d, 0xb3, 0x26, 0xee, 0x10, 0x00,
	0xff, 0x7d, 0x53, 0x32, 0x5e, 0xc4, 0x8e, 0xa6, 0xf1, 0x86, 0xd8, 0x25, 0x5b, 0x10, 0xd8, 0xa7,
	0x63, 0x4f, 0x9f, 0xb9, 0x10, 0x4d, 0x45, 0xe7, 0x71, 0x57, 0x4f, 0x39, 0xe3, 0x82, 0x2f, 0x2a,
	0xd1, 0xca, 0xb8, 0x67, 0x5a, 0x7a, 0xe1, 0xd8, 0x3f, 0x79, 0x05, 0x7b, 0xf7, 0xbc, 0xd3, 0xa7,
	0xcd, 0xed, 0x67, 0x45, 0x11, 0x77, 0xc8, 0x36, 0x84, 0x38, 0x40, 0x23, 0x47, 0x6f, 0x88, 0x68,
	0xc8, 0x6f, 0x4a, 0xc5, 0x62, 0xf7, 0xf4, 0x8f, 0x03, 0xfe, 0x25, 0xfe, 0x03, 0xc8, 0x6b, 0xd8,
	0xb9, 0x13, 0x4f, 0xd2, 0xcf, 0xd6, 0x7d, 0xb2, 0x83, 0x83, 0x6c, 0x6d, 0x8a, 0xd3, 0x0e, 0xf9,
	0x08, 0x0f, 0xfe, 0xb3, 0x93, 0x1c, 0x66, 0x9b, 0x62, 0x38, 0x18, 0x64, 0x1b, 0xdd, 0x4f, 0x3b,
	0xe4, 0x25, 0x6c, 0xaf, 0xda, 0x43, 0xf6, 0xb3, 0x35, 0x26, 0x0e, 0xfa, 0xd9, 0x3a, 0x0f, 0xd3,
	0xce, 0xd8, 0xc7, 0x7f, 0xda, 0x8b, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x23, 0x8c, 0x80, 0xab,
	0xe3, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PluginClient interface {
	HandleMessage(ctx context.Context, in *HandleMessageRequest, opts ...grpc.CallOption) (*HandleMessageResponse, error)
	HandleApplication(ctx context.Context, in *HandleApplicationRequest, opts ...grpc.CallOption) (*HandleApplicationResponse, error)
	HandleNotice(ctx context.Context, in *HandleNoticeRequest, opts ...grpc.CallOption) (*HandleNoticeResponse, error)
}

type pluginClient struct {
	cc *grpc.ClientConn
}

func NewPluginClient(cc *grpc.ClientConn) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) HandleMessage(ctx context.Context, in *HandleMessageRequest, opts ...grpc.CallOption) (*HandleMessageResponse, error) {
	out := new(HandleMessageResponse)
	err := c.cc.Invoke(ctx, "/Plugin/HandleMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) HandleApplication(ctx context.Context, in *HandleApplicationRequest, opts ...grpc.CallOption) (*HandleApplicationResponse, error) {
	out := new(HandleApplicationResponse)
	err := c.cc.Invoke(ctx, "/Plugin/HandleApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) HandleNotice(ctx context.Context, in *HandleNoticeRequest, opts ...grpc.CallOption) (*HandleNoticeResponse, error) {
	out := new(HandleNoticeResponse)
	err := c.cc.Invoke(ctx, "/Plugin/HandleNotice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
type PluginServer interface {
	HandleMessage(context.Context, *HandleMessageRequest) (*HandleMessageResponse, error)
	HandleApplication(context.Context, *HandleApplicationRequest) (*HandleApplicationResponse, error)
	HandleNotice(context.Context, *HandleNoticeRequest) (*HandleNoticeResponse, error)
}

// UnimplementedPluginServer can be embedded to have forward compatible implementations.
type UnimplementedPluginServer struct {
}

func (*UnimplementedPluginServer) HandleMessage(ctx context.Context, req *HandleMessageRequest) (*HandleMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleMessage not implemented")
}
func (*UnimplementedPluginServer) HandleApplication(ctx context.Context, req *HandleApplicationRequest) (*HandleApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleApplication not implemented")
}
func (*UnimplementedPluginServer) HandleNotice(ctx context.Context, req *HandleNoticeRequest) (*HandleNoticeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleNotice not implemented")
}

func RegisterPluginServer(s *grpc.Server, srv PluginServer) {
	s.RegisterService(&_Plugin_serviceDesc, srv)
}

func _Plugin_HandleMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).HandleMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plugin/HandleMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).HandleMessage(ctx, req.(*HandleMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_HandleApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).HandleApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plugin/HandleApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).HandleApplication(ctx, req.(*HandleApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_HandleNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleNoticeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).HandleNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plugin/HandleNotice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).HandleNotice(ctx, req.(*HandleNoticeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Plugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleMessage",
			Handler:    _Plugin_HandleMessage_Handler,
		},
		{
			MethodName: "HandleApplication",
			Handler:    _Plugin_HandleApplication_Handler,
		},
		{
			MethodName: "HandleNotice",
			Handler:    _Plugin_HandleNotice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
